# Generated by Django 3.2.7 on 2021-09-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('parentesco', models.CharField(max_length=255)),
                ('telefone1', models.CharField(max_length=255)),
                ('telefone2', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pre-tarv', 'pre-tarv'), ('tarv', 'tarv')], max_length=50)),
                ('numero', models.IntegerField()),
                ('pagina', models.IntegerField()),
                ('linha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TesteHivPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_teste', models.CharField(choices=[('TR', 'TR'), ('PCRE', 'PCRE')], max_length=10)),
                ('data_teste', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distrito')),
            ],
            options={
                'verbose_name': 'Unidade Sanitaria',
                'verbose_name_plural': 'Unidades Sanitarias',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=20)),
                ('data_nascimento', models.DateTimeField()),
                ('nid', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('confidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.confidente')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.livro')),
            ],
        ),
        migrations.CreateModel(
            name='FichaResumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField()),
                ('hepatite', models.BooleanField(default=False)),
                ('data_hepatite', models.DateTimeField(blank=True, null=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('data_diabetes', models.DateTimeField(blank=True, null=True)),
                ('tb', models.BooleanField(default=False)),
                ('data_tb', models.DateTimeField(blank=True, null=True)),
                ('hta', models.BooleanField(default=False)),
                ('data_hta', models.DateTimeField(blank=True, null=True)),
                ('criptococose', models.BooleanField(default=False)),
                ('data_criptococose', models.DateTimeField(blank=True, null=True)),
                ('s_kapose', models.BooleanField(default=False)),
                ('data_kapose', models.DateTimeField(blank=True, null=True)),
                ('via_positivo', models.BooleanField(default=False)),
                ('data_via', models.DateTimeField(blank=True, null=True)),
                ('outra', models.CharField(blank=True, max_length=255, null=True)),
                ('data_outra', models.DateTimeField(blank=True, null=True)),
                ('ultimo_cd4', models.IntegerField()),
                ('data_cd4', models.DateTimeField(blank=True, null=True)),
                ('ultima_cv', models.IntegerField()),
                ('data_cv', models.DateTimeField(null=True)),
                ('ultima_ctz_data_inicio', models.DateTimeField(blank=True, null=True)),
                ('ultima_ctz_data_fim', models.DateTimeField(null=True)),
                ('teste_hiv_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testehivpos')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
    ]
