# Generated by Django 3.2.7 on 2021-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
